spring.application.name=ArenaHub
spring.datasource.url=jdbc:mysql://localhost:3306/arenahub
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD}

spring.data.redis.host=localhost
spring.data.redis.port=6379